version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
