# Generated by Django 4.2.9 on 2024-10-07 18:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('socia_networks', models.JSONField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('account_status', models.BooleanField(default=True)),
                ('last_activity_date', models.DateTimeField(auto_now=True)),
                ('address', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
        ),
    ]
